//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the different sources from which the calibration files can be acquired.
public enum CalibrationFileSource {
  ///  The calibration files are fetched from the on-board memory of the device. Not supported by all devices.
  Device,
  ///  The calibration files are copied from a local filesystem directory.
  Filesystem,
  ///  The calibration files are downloaded from Optris servers. Requires internet access.
  Internet,
  ///  No calibration source wanted.
  Empty
}

}
