//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

/// <summary>Represents the different available color formats.</summary>
/// The format defines the storage __sequence__ of the pixel color values. Therefore, the color value of the first letter will come
/// first in the image pixel value array.
/// Some systems refer to the __significance__ of the color values as color format. Here the color value of the first letter is the most
/// significant byte. On big-endian machines this byte comes first. On little-endian machines it will come last.
/// faulty_color_format.jpg"False color image with Iron color palette: Left correct color format, right wrong color format."
public enum ColorFormat {
  ///  Pixel colors values are stored in the sequence: (red, green, blue).
  RGB,
  ///  Pixel colors values are stored in the sequence: (blue, green, red).
  BGR
}

}
