//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

/// <summary>Represents the available coloring palettes.</summary>
public enum ColoringPalette {
  ///  color_palette_alarm_blue.jpg
  AlarmBlue,
  ///  color_palette_alarm_blue_hi.jpg
  AlarmBlueHi,
  ///  color_palette_gray_bw.jpg
  GrayBW,
  ///  color_palette_gray_wb.jpg
  GrayWB,
  ///  color_palette_alarm_green.jpg
  AlarmGreen,
  ///  color_palette_iron.jpg
  Iron,
  ///  color_palette_iron_hi.jpg
  IronHi,
  ///  color_palette_medical.jpg
  Medical,
  ///  color_palette_rainbow.jpg
  Rainbow,
  ///  color_palette_rainbow_hi.jpg
  RainbowHi,
  ///  color_palette_alarm_red.jpg
  AlarmRed
}

}
