//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
///  Iterates over the frame in a row major fashion and grants read access.

public class ConstFrameIterator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConstFrameIterator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConstFrameIterator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConstFrameIterator obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConstFrameIterator() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_ConstFrameIterator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <summary>Constructor.</summary>
  /// <param name="frame"> to iterate over.</param>
  public ConstFrameIterator(Frame frame) : this(otcsdkPINVOKE.new_ConstFrameIterator(Frame.getCPtr(frame)), true) {
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Returns whether there is a next frame value.</summary>
  /// <returns>true if there is a next frame value. False otherwise.</returns>
  public bool hasNext() {
    bool ret = otcsdkPINVOKE.ConstFrameIterator_hasNext(swigCPtr);
    return ret;
  }

  ///  Moves to the next frame value.
  public void next() {
    otcsdkPINVOKE.ConstFrameIterator_next(swigCPtr);
  }

  /// <summary>Returns the current frame value.</summary>
  /// <returns>current frame value.</returns>
  public ushort getValue() {
    ushort ret = otcsdkPINVOKE.ConstFrameIterator_getValue(swigCPtr);
    return ret;
  }

  /// <summary>Returns the index of the current frame value.</summary>
  /// <returns>index of the current frame value.</returns>
  public int getIndex() {
    int ret = otcsdkPINVOKE.ConstFrameIterator_getIndex(swigCPtr);
    return ret;
  }

  /// <summary>Returns the x-coordinate of the current frame value.</summary>
  /// <returns>x-coordinate of the current frame value.</returns>
  public int getX() {
    int ret = otcsdkPINVOKE.ConstFrameIterator_getX(swigCPtr);
    return ret;
  }

  /// <summary>Returns the y-coordinate of the current frame value.</summary>
  /// <returns>y-coordinate of the current frame value.</returns>
  public int getY() {
    int ret = otcsdkPINVOKE.ConstFrameIterator_getY(swigCPtr);
    return ret;
  }

}

}
