//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
///  Iterates over a measurement field in a row major fashion and grants read access.

public class ConstMeasurementFieldIterator : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConstMeasurementFieldIterator(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConstMeasurementFieldIterator obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ConstMeasurementFieldIterator obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ConstMeasurementFieldIterator() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_ConstMeasurementFieldIterator(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  /// <summary>Constructor.</summary>
  /// <param name="field"> measurement field to iterate over.</param>
  public ConstMeasurementFieldIterator(MeasurementField field) : this(otcsdkPINVOKE.new_ConstMeasurementFieldIterator(MeasurementField.getCPtr(field)), true) {
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Returns whether there is a next measurement field value.</summary>
  /// <returns>true if there is a next measurement field value. False otherwise.</returns>
  public bool hasNext() {
    bool ret = otcsdkPINVOKE.ConstMeasurementFieldIterator_hasNext(swigCPtr);
    return ret;
  }

  ///  Moves to the next measurement field value.
  public void next() {
    otcsdkPINVOKE.ConstMeasurementFieldIterator_next(swigCPtr);
  }

  /// <summary>Returns the current measurement field value.</summary>
  /// <returns>current measurement field value.</returns>
  public ushort getValue() {
    ushort ret = otcsdkPINVOKE.ConstMeasurementFieldIterator_getValue(swigCPtr);
    return ret;
  }

  /// <summary>Returns the index of the current measurement field value.</summary>
  /// <returns>index of the current measurement field value.</returns>
  public int getIndex() {
    int ret = otcsdkPINVOKE.ConstMeasurementFieldIterator_getIndex(swigCPtr);
    return ret;
  }

  /// <summary>Returns the x-coordinate of the current measurement field value.</summary>
  /// <returns>x-coordinate of the current measurement field value.</returns>
  public int getX() {
    int ret = otcsdkPINVOKE.ConstMeasurementFieldIterator_getX(swigCPtr);
    return ret;
  }

  /// <summary>Returns the y-coordinate of the current measurement field value.</summary>
  /// <returns>y-coordinate of the current measurement field value.</returns>
  public int getY() {
    int ret = otcsdkPINVOKE.ConstMeasurementFieldIterator_getY(swigCPtr);
    return ret;
  }

}

}
