//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the different types of Optris thermal cameras.
public enum DeviceType {
  Unknown,
  PI1,
  PI160,
  PI2x0,
  PI160orPI2x0,
  PI4x0,
  PI4x0I,
  PI640,
  PI640I,
  PI1M,
  Xi80,
  Xi160,
  Xi400,
  Xi410,
  Xi410MT,
  Xi440,
  Xi640,
  Xi1M
}

}
