//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {
/// <summary>Defines the interface for classes that want to be updated about the detection of       available devices.</summary>

public class EnumerationClient : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EnumerationClient(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EnumerationClient obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(EnumerationClient obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~EnumerationClient() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          otcsdkPINVOKE.delete_EnumerationClient(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  ///  Constructor.
  public EnumerationClient() : this(otcsdkPINVOKE.new_EnumerationClient__SWIG_0(), true) {
    SwigDirectorConnect();
  }

  ///  No copy constructor.
  public EnumerationClient(EnumerationClient arg0) : this(otcsdkPINVOKE.new_EnumerationClient__SWIG_1(EnumerationClient.getCPtr(arg0)), true) {
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
    SwigDirectorConnect();
  }

  /// <summary>Callback function triggered when a new available device is detected.</summary>
  /// <param name="deviceInfo"> information of the device.</param>
  public virtual void onDeviceDetected(DeviceInfo deviceInfo) {
    if (SwigDerivedClassHasMethod("onDeviceDetected", swigMethodTypes0)) otcsdkPINVOKE.EnumerationClient_onDeviceDetectedSwigExplicitEnumerationClient(swigCPtr, DeviceInfo.getCPtr(deviceInfo)); else otcsdkPINVOKE.EnumerationClient_onDeviceDetected(swigCPtr, DeviceInfo.getCPtr(deviceInfo));
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  /// <summary>Callback function triggered when a previously detected available device is no longer detected.</summary>
  /// <param name="deviceInfo"> information of the device.</param>
  public virtual void onDeviceDetectionLost(DeviceInfo deviceInfo) {
    if (SwigDerivedClassHasMethod("onDeviceDetectionLost", swigMethodTypes1)) otcsdkPINVOKE.EnumerationClient_onDeviceDetectionLostSwigExplicitEnumerationClient(swigCPtr, DeviceInfo.getCPtr(deviceInfo)); else otcsdkPINVOKE.EnumerationClient_onDeviceDetectionLost(swigCPtr, DeviceInfo.getCPtr(deviceInfo));
    if (otcsdkPINVOKE.SWIGPendingException.Pending) throw otcsdkPINVOKE.SWIGPendingException.Retrieve();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("onDeviceDetected", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateEnumerationClient_0(SwigDirectorMethodonDeviceDetected);
    if (SwigDerivedClassHasMethod("onDeviceDetectionLost", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateEnumerationClient_1(SwigDirectorMethodonDeviceDetectionLost);
    otcsdkPINVOKE.EnumerationClient_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(EnumerationClient))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private void SwigDirectorMethodonDeviceDetected(global::System.IntPtr deviceInfo) {
    onDeviceDetected(new DeviceInfo(deviceInfo, true));
  }

  private void SwigDirectorMethodonDeviceDetectionLost(global::System.IntPtr deviceInfo) {
    onDeviceDetectionLost(new DeviceInfo(deviceInfo, true));
  }

  public delegate void SwigDelegateEnumerationClient_0(global::System.IntPtr deviceInfo);
  public delegate void SwigDelegateEnumerationClient_1(global::System.IntPtr deviceInfo);

  private SwigDelegateEnumerationClient_0 swigDelegate0;
  private SwigDelegateEnumerationClient_1 swigDelegate1;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(DeviceInfo) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(DeviceInfo) };
}

}
