//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

/// <summary>Represents the different states of the shutter flag.</summary>
/// A flag cycle is defined by the transition through the following states:
///  Open - Closing - Closed - Opening - Open
/// During the automated startup calibration after a successful device connection the flag
/// state will be Initializing indicating the thermal frame data is not yet reliable.
public enum FlagState {
  ///  Flag is open.
  Open,
  ///  Flag is closed.
  Closed,
  ///  Flag is opening.
  Opening,
  ///  Flag is closing.
  Closing,
  ///  Flag is in an error state.
  Error,
  ///  Flag state is beeing initialized/calibrated.
  Initializing
}

}
