//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

public class otcsdk {
  /// <summary>Returns a string representation of the given device type.</summary>
  /// <param name="deviceType"> for which a string representation is desired.</param> 
  /// <returns>string respresentation of the given device type.</returns>
  public static string toString(DeviceType deviceType) {
    string ret = otcsdkPINVOKE.toString__SWIG_0((int)deviceType);
    return ret;
  }

  /// <summary>Returns a string representation of the given flag state.</summary>
  /// <returns>string representation of the given flag state.</returns>
  public static string toString(FlagState flagState) {
    string ret = otcsdkPINVOKE.toString__SWIG_1((int)flagState);
    return ret;
  }

  public static float INVALID_TEMPERATURE {
    get {
      float ret = otcsdkPINVOKE.INVALID_TEMPERATURE_get();
      return ret;
    } 
  }

  public static ushort INVALID_VALUE {
    get {
      ushort ret = otcsdkPINVOKE.INVALID_VALUE_get();
      return ret;
    } 
  }

}

}
