//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the false color conversion strategies.
public enum PaletteScalingMethod {
  ///  User-defined upper and lower limit (fixed values).
  Manual,
  ///  Dynamic determination of minimum and maximum temperature as upper and lower limit.
  MinMax,
  ///  Dynamic determination of upper and lower limit from standard deviation of temperature image.
  Sigma1,
  ///  Same as eSigma1, but with factor 3.
  Sigma3
}

}
