//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the different triggers of an event.
public enum SnapshotTrigger {
  ///  Triggered by digital input.
  DigitalInput,
  ///  Triggered by analog input.
  AnalogInput,
  ///  Triggered by software.
  Software
}

}
