//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the different event types.
public enum SnapshotType {
  ///  Event source is snapshot.
  Snapshot,
  ///  Event source is snapshot on edge.
  SnapshotOnEdge
}

}
