//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the available temperature precisions.
public enum TemperaturePrecision {
  ///  Unknown precision.
  Unknown = 0,
  ///  Standard precision.
  Standard = 1,
  ///  Hight precision.
  High = 2
}

}
