//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

///  Represents the different logging verbosity levels.
public enum Verbosity {
  ///  Off.
  Off = 1,
  ///  Error.
  Error = 2,
  ///  Warning.
  Warning = 3,
  ///  Info.
  Info = 4,
  ///  Debug.
  Debug = 5
}

}
