//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Optris.OtcSDK {

/// <summary>Represents the different available width alignments.</summary>
/// Depending on the chosen alignment additional bytes will be added to the end of each row in an image so that its size in bytes adheres
/// to that alignment. This enables some frame works like OpenGL to read the image data in bigger chunks than one byte at a time which
/// can result in significant performance benefits.
/// faulty_width_alignment.jpg"Example false color image with faulty width alignment."
public enum WidthAlignment {
  ///  The row size is aligned to one byte.
  OneByte = 1,
  ///  The row size is aligned to two bytes.
  TwoBytes = 2,
  ///  The row size is aligned to four bytes.
  FourBytes = 4,
  ///  The row size is aligned to eight bytes.
  EightBytes = 8
}

}
